### ISSUE TITLE
N1 旁路由ADH 配置求助

### ISSUE THREAD

**Issue by my5xhni** [Hlynford/Acer-E5-572G-528R-Hackintosh#1]
大神有问题求助。
![image](https://user-images.githubusercontent.com/16264838/81206691-0d40bb80-8fff-11ea-8ec6-d0c4289c8148.png)
软件环境：OpenWrt R20.4.8 (Lean源码编译) 路由器安装的ADH非Docker
已注释其 53端口转发的规则
![image](https://user-images.githubusercontent.com/16264838/81206992-77f1f700-8fff-11ea-8e5e-a96cd2bb8815.png)
按照你博客文章里面进行配置，ADH常规设置下面的 安全浏览/家庭控制/强制安全搜索（功能失效，测试了几个H网没有被拦截）
日志报错
![image](https://user-images.githubusercontent.com/16264838/81207197-c69f9100-8fff-11ea-8c30-1ccd5ba58726.png)
 还有一个就是 能否把本博文 增加一个 ADH+出国留学Plus + 协同工作的 配置教程呢？

谢谢大神了，在这里开个ISSUS非常抱歉，如果有冒犯到你还请见谅，因为你的博客下面不支持留言（需要登陆权限）。

**Comment by Hlynford** [comment]
你好，博客注册功能暂未完善，博客内不想涉及关于出国留学方面内容。关于这个无法过滤的问题：
1.检查Openwrt网络状态，是否能正常上网
2.检查AdGuardHome内的DNS设置后，是否可以可以测试连接成功
3.检查过滤规则是否存在，可依靠过滤规则拦截内容
4.AdGuardHome内置的那个几个”安全浏览/家庭控制/强制安全搜索“的dns不确保在国内可以正常访问，可以尝试先本机电脑ping那个dns看是否能ping通
5.旁路由模式，检查旁路由DNS是否已经设置为127.0.0.1#1153，设备是连接主路由的话，主路由的DNS需要设置为openwrt的地址，而不是运营商的dns或者主路由自己的dns，同时检查本机电脑获取的dns情况，设置后重新连接本机网络（如wifi或者以太网）

**Comment by Hlynford** [comment]
> 大神有问题求助。
> ![image](https://user-images.githubusercontent.com/16264838/81206691-0d40bb80-8fff-11ea-8ec6-d0c4289c8148.png)
> 软件环境：OpenWrt R20.4.8 (Lean源码编译) 路由器安装的ADH非Docker
> 已注释其 53端口转发的规则
> ![image](https://user-images.githubusercontent.com/16264838/81206992-77f1f700-8fff-11ea-8e5e-a96cd2bb8815.png)
> 按照你博客文章里面进行配置，ADH常规设置下面的 安全浏览/家庭控制/强制安全搜索（功能失效，测试了几个H网没有被拦截）
> 日志报错
> ![image](https://user-images.githubusercontent.com/16264838/81207197-c69f9100-8fff-11ea-8c30-1ccd5ba58726.png)
> 还有一个就是 能否把本博文 增加一个 ADH+出国留学Plus + 协同工作的 配置教程呢？
> 
> 谢谢大神了，在这里开个ISSUS非常抱歉，如果有冒犯到你还请见谅，因为你的博客下面不支持留言（需要登陆权限）。



> 大神有问题求助。
> ![image](https://user-images.githubusercontent.com/16264838/81206691-0d40bb80-8fff-11ea-8ec6-d0c4289c8148.png)
> 软件环境：OpenWrt R20.4.8 (Lean源码编译) 路由器安装的ADH非Docker
> 已注释其 53端口转发的规则
> ![image](https://user-images.githubusercontent.com/16264838/81206992-77f1f700-8fff-11ea-8e5e-a96cd2bb8815.png)
> 按照你博客文章里面进行配置，ADH常规设置下面的 安全浏览/家庭控制/强制安全搜索（功能失效，测试了几个H网没有被拦截）
> 日志报错
> ![image](https://user-images.githubusercontent.com/16264838/81207197-c69f9100-8fff-11ea-8c30-1ccd5ba58726.png)
> 还有一个就是 能否把本博文 增加一个 ADH+出国留学Plus + 协同工作的 配置教程呢？
> 
> 谢谢大神了，在这里开个ISSUS非常抱歉，如果有冒犯到你还请见谅，因为你的博客下面不支持留言（需要登陆权限）。

你好，博客注册功能暂未完善，博客内不想涉及关于出国留学方面内容。关于这个无法过滤的问题：
1.检查Openwrt网络状态，是否能正常上网
2.检查AdGuardHome内的DNS设置后，是否可以可以测试连接成功
3.检查过滤规则是否存在，可依靠过滤规则拦截内容
4.AdGuardHome内置的那个几个”安全浏览/家庭控制/强制安全搜索“的dns不确保在国内可以正常访问，可以尝试先本机电脑ping那个dns看是否能ping通
5.旁路由模式，检查旁路由DNS是否已经设置为127.0.0.1#1153，设备是连接主路由的话，主路由的DNS需要设置为openwrt的地址，而不是运营商的dns或者主路由自己的dns，同时检查本机电脑获取的dns情况，设置后重新连接本机网络（如wifi或者以太网）

**Comment by my5xhni** [comment]
DNS过滤器是可以正常工作的，就是内置 安全浏览/家长控制/安全搜索不能用，这3个DNS可以ping通就是感觉很疑惑为什么还报错。

如果不是把ADH配置为上游DNS，而将其设置为53端口重定向（出国留学 功夫网模式又失效了，有点鱼和熊掌不可兼得的感觉），那么至少家庭控制的功能就能正常运行了。

可能 还是 DNS 解析服务器的优先级导致了 解析混乱吧。

**Comment by Hlynford** [comment]
> DNS过滤器是可以正常工作的，就是内置 安全浏览/家长控制/安全搜索不能用，这3个DNS可以ping通就是感觉很疑惑为什么还报错。
> 
> 如果不是把ADH配置为上游DNS，而将其设置为53端口重定向（出国留学 功夫网模式又失效了，有点鱼和熊掌不可兼得的感觉），那么至少家庭控制的功能就能正常运行了。
> 
> 可能 还是 DNS 解析服务器的优先级导致了 解析混乱吧。

我这边可能暂时无法还原你的情况，我用的OpenWrt是恩山flippy提供的包，可看看能否解决你的这个问题
